### ISSUE TITLE
Error "A Referral was returned from the server"

### ISSUE THREAD

**Issue by 1F1R5T** [GoogleX133/SubdomainEnum#1]
![Capture](https://user-images.githubusercontent.com/26076138/59352929-10c6b680-8d4c-11e9-93d0-43ef3e9b6c8b.PNG)

**Comment by GoogleX133** [comment]
Try this [solution](https://www.repairwin.com/fix-a-referral-was-returned-from-the-server-error/).

NOTE: *There are 2 solution that you can try one or all of the solution.

**Comment by GoogleX133** [comment]
I have released a new version, Check it out!

**Comment by GoogleX133** [comment]
Sorry for my late response :(
